### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by bertocq** [folkswhocode/diversifaq#8]
Hi! I talked with @dreamingechoes about what would be the best way to organize files for different languages as I was going to send some PR's to translate existing files on to english/spanish.

I guess being consistent with https://github.com/folkswhocode/base is the way to go: LICENSE & README.md on english at root level, plus `/en` & `/es` directories with everything else. If it is so, just 👍  and I'll get my hands into it :) (I've 10+ hours of train next week)

**Comment by dreamingechoes** [comment]
Hi @bertocq!

Perfect! Yeah, it would be awesome if we follow the structure of the [base](https://github.com/folkswhocode/base) project, in terms of folders and organization, so if you want you can address this and make the PR 😄 

Thank you very much! ❤️

**Comment by marinavega** [comment]
I agree. Our base project structure is a good starting point 😸 

Thanks for your time, @bertocq ✨
